"""
Django settings for naren_ultrasound project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-radm@l&!3xn^le31)=6sg7st8de!_yqiz8^%@sflr)h_*gv=39'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'www.narenultrasound.in',
    'narenultrasound.in',
    '.vercel.app',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website',
    "tailwind",
    "theme",
    'django.contrib.sitemaps',
    'django_ckeditor_5',
]

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': {
            'items': [
                'heading',

                '|',

                'bold',
                'italic',
                'underline',
                'strikethrough',

                '|',

                'bulletedList',
                'numberedList',

                '|',

                'link',
                'blockQuote',
                'insertTable',

                '|',

                'undo',
                'redo',
            ]
        }
    }
}

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'naren_ultrasound.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'naren_ultrasound.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'neondb',
        'USER': 'neondb_owner',
        'PASSWORD': 'npg_YoATlL54rKyw',
        'HOST': 'ep-restless-sun-ator3vwd.c-9.us-east-1.aws.neon.tech',
        'PORT': '5432',
        'OPTIONS': {
            'sslmode': 'require',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

TAILWIND_APP_NAME = "theme"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'website/static'),
]

# User-uploaded files (blog featured images, gallery, services).
# MEDIA_URL is what the browser requests, MEDIA_ROOT is where the bytes live
# on disk. Both are also used by ImageField.url / FileSystemStorage, so they
# must stay in sync - never build a media URL by hand in a template.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Make sure the media tree exists before the first upload, otherwise the very
# first ImageField save on a fresh checkout fails. Guarded because some hosts
# (Vercel) mount the deployment bundle read-only.
for _media_dir in ('blog', 'blog/photos'):
    try:
        os.makedirs(os.path.join(MEDIA_ROOT, _media_dir), exist_ok=True)
    except OSError:
        pass

# Django 5.1+ ignores the old DEFAULT_FILE_STORAGE / STATICFILES_STORAGE
# settings - they must be declared through STORAGES instead. Without this the
# whitenoise static backend was silently ignored, and 'default' is what
# ImageField uses to write into MEDIA_ROOT.
#
# 'default' is the single switch for every uploaded image on the site
# (featured images, gallery, services, and blog client photos) - they all go
# through an ImageField, so none of them need code changes to move.
#
# Vercel's filesystem is read-only and thrown away on each deploy, so anything
# written there at runtime is lost. Point DJANGO_MEDIA_STORAGE_BACKEND at a
# persistent backend (e.g. 'storages.backends.s3.S3Storage' or Cloudinary) in
# the Vercel environment to make uploads survive; the local default keeps
# development working off MEDIA_ROOT.
STORAGES = {
    'default': {
        'BACKEND': os.environ.get(
            'DJANGO_MEDIA_STORAGE_BACKEND',
            'django.core.files.storage.FileSystemStorage',
        ),
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# ChatGPT-generated PNGs run around 2 MB. Keep a single image in memory, and
# leave enough headroom for the CKEditor body posted alongside it.
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024

# Largest remote image we are willing to pull in from a ChatGPT/OpenAI URL.
BLOG_IMAGE_DOWNLOAD_MAX_BYTES = 20 * 1024 * 1024
BLOG_IMAGE_DOWNLOAD_TIMEOUT = 30

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True


EMAIL_HOST_USER = 'narenultrasound@gmail.com'

EMAIL_HOST_PASSWORD = 'iadj snhw ufwz vhed'