# Generated by Django 6.0.5 on 2026-06-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_blogpost_seo_description_blogpost_seo_keywords_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='short_description',
            new_name='meta_description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='seo_title',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Dr. Naren Satya', max_length=100),
        ),
    ]
