# Generated by Django 6.0.5 on 2026-06-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_blogcategory_blogtag_remove_blogpost_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Dr.Naren-Satya', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
