# Generated by Django 6.0.5 on 2026-08-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_blogpost_author_alter_blogtag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Dr. Naren Satya', max_length=100),
        ),
    ]
