# Generated by Django 6.0.5 on 2026-08-29 10:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_blogpost_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='JPG, JPEG or PNG.', upload_to='blog/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('caption', models.CharField(blank=True, help_text='Optional. Shown under the photo, and used as its alt text.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the gallery.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_photos', to='website.blogpost')),
            ],
            options={
                'verbose_name': 'Client photo',
                'verbose_name_plural': 'Client photos',
                'ordering': ['order', 'id'],
            },
        ),
    ]
