# Generated by Django 6.0.5 on 2026-08-29 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_blogphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dr. Naren Satya', max_length=150)),
                ('designation', models.CharField(default='Consultant Radiologist', max_length=200)),
                ('organisation', models.CharField(blank=True, default='Naren Ultrasound and Fetal Medicine Center, Visakhapatnam', help_text='Centre and city, shown under the designation.', max_length=250)),
                ('photo', models.ImageField(blank=True, help_text='Uploaded once and reused on every blog post.', upload_to='doctor/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('bio', models.TextField(blank=True, help_text='Optional. A short paragraph shown beside the photo.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide the doctor section from all blog posts.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor profile',
                'verbose_name_plural': 'Doctor profile',
            },
        ),
    ]
